global:
  resolve_timeout: 1m

route:
  receiver: homepage-alerts
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 4h

receivers:
  - name: homepage-alerts
    webhook_configs:
      - url: http://alert-webhook:5001/alert
